source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'

install! 'cocoapods', integrate_targets: false

platform :ios, '12.0'

target 'FooBar' do
  pod 'ServiceSDK'
end
